/** Curated + generated pool for hangman (200+). */
const HANGMAN_CORE = [
  "moonlight", "whisper", "velvet", "harbor", "cipher", "lantern", "midnight",
  "echo", "mirror", "shadow", "ember", "frost", "thunder", "cascade", "oracle",
  "labyrinth", "nebula", "quartz", "voyage", "wander", "zephyr", "alchemy",
  "ballad", "cathedral", "dragon", "enigma", "fortune", "galaxy", "horizon",
  "illusion", "jasmine", "kingdom", "legend", "mystery", "nostalgia", "oasis",
  "phantom", "quiver", "riddle", "symphony", "tapestry", "umbrella", "violet",
  "willow", "xenon", "yearning", "zenith", "amber", "blossom", "crimson",
  "dusk", "eclipse", "fable", "glimmer", "haven", "ivory", "journey", "kindred",
  "lullaby", "meadow", "nightfall", "obsidian", "paradox", "quaint", "radiant",
  "solstice", "twilight", "aurora", "breeze", "cobalt", "dream", "eternal",
  "flame", "garden", "harmony", "infinite", "jewel", "karma", "liberty",
  "melody", "noble", "ocean", "prism", "quest", "ripple", "serene", "temple",
  "unity", "vintage", "wisdom", "yarn", "zeppelin", "atlas", "bramble",
  "compass", "destiny", "element", "falcon", "griffin", "halcyon", "icon",
  "jupiter", "knight", "lotus", "marble", "nimbus", "opal", "puzzle", "quorum",
  "raven", "sphinx", "titan", "oracle", "vortex", "walnut", "yarn", "yonder",
  "alchemy", "basilisk", "citadel", "dirigible", "epoch", "fable", "glyph",
  "hearth", "incense", "jade", "kelp", "lumen", "mantle", "nautilus", "omen",
  "parchment", "quasar", "rook", "scepter", "talisman", "urn", "vagrant",
  "wraith", "axiom", "bard", "chisel", "driftwood", "epoch", "fjord", "grotto",
  "hinterland", "iris", "juniper", "kraken", "lore", "monsoon", "nova",
  "observatory", "petrichor", "quiver", "reef", "summit", "torrent", "undine",
  "vertex", "wisp", "yew", "zen", "arcane", "brook", "cinder", "dew", "elm",
  "fable", "gale", "hollow", "idol", "jester", "keystone", "lattice", "mirth",
  "nymph", "oracle", "plume", "quill", "rune", "sable", "tome", "urn",
  "vale", "warden", "xylem", "yield", "zodiac",
];

const HANGMAN_SUFFIX = ["", "s", "ly", "ing", "ed", "ness"];
export const HANGMAN_WORDS: string[] = (() => {
  const set = new Set<string>(HANGMAN_CORE);
  for (const w of HANGMAN_CORE) {
    for (const s of HANGMAN_SUFFIX) {
      const t = `${w}${s}`;
      if (t.length >= 4 && t.length <= 14) set.add(t);
    }
  }
  return Array.from(set).filter((w) => /^[a-z]+$/i.test(w));
})();

export const WORD_CHAIN_ANIMALS: string[] = [
  "aardvark", "albatross", "alligator", "alpaca", "ant", "anteater", "antelope",
  "ape", "armadillo", "baboon", "badger", "barracuda", "bat", "bear", "beaver",
  "bee", "beetle", "bison", "boar", "buffalo", "butterfly", "camel", "caribou",
  "cat", "caterpillar", "chameleon", "cheetah", "chicken", "chimpanzee",
  "chinchilla", "clam", "cobra", "cockroach", "cod", "cougar", "cow", "coyote",
  "crab", "crane", "crocodile", "crow", "deer", "dinosaur", "dog", "dolphin",
  "donkey", "dove", "dragonfly", "duck", "eagle", "eel", "elephant", "elk",
  "emu", "falcon", "ferret", "finch", "fish", "flamingo", "fly", "fox", "frog",
  "gazelle", "gecko", "gerbil", "giraffe", "goat", "goose", "gorilla",
  "grasshopper", "gull", "hamster", "hare", "hawk", "hedgehog", "heron",
  "hippopotamus", "hornet", "horse", "hummingbird", "hyena", "ibex", "iguana",
  "jackal", "jaguar", "jellyfish", "kangaroo", "kingfisher", "koala", "krill",
  "ladybug", "lemur", "leopard", "lion", "lizard", "llama", "lobster", "locust",
  "lynx", "macaw", "magpie", "mallard", "manatee", "mandrill", "mantis",
  "meerkat", "mink", "mole", "mongoose", "monkey", "moose", "mosquito", "mouse",
  "narwhal", "newt", "nightingale", "octopus", "opossum", "orangutan", "orca",
  "ostrich", "otter", "owl", "ox", "oyster", "panda", "panther", "parrot",
  "peacock", "pelican", "penguin", "pheasant", "pig", "pigeon", "platypus",
  "polar bear", "pony", "porcupine", "porpoise", "puffin", "python", "quail",
  "rabbit", "raccoon", "ram", "rat", "raven", "reindeer", "rhinoceros", "roach",
  "robin", "salamander", "salmon", "scorpion", "seahorse", "seal", "shark",
  "sheep", "shrimp", "skunk", "sloth", "snail", "snake", "sparrow", "spider",
  "squid", "squirrel", "starfish", "stingray", "stork", "swan", "tapir", "tiger",
  "toad", "toucan", "turkey", "turtle", "viper", "vulture", "wallaby", "walrus",
  "wasp", "weasel", "whale", "wolf", "wolverine", "wombat", "woodpecker", "yak",
  "zebra",
];

export const WORD_CHAIN_COUNTRIES: string[] = [
  "afghanistan", "albania", "algeria", "andorra", "angola", "argentina",
  "armenia", "australia", "austria", "azerbaijan", "bahamas", "bahrain",
  "bangladesh", "barbados", "belarus", "belgium", "belize", "benin", "bhutan",
  "bolivia", "bosnia", "botswana", "brazil", "brunei", "bulgaria", "burkina faso",
  "burundi", "cambodia", "cameroon", "canada", "chad", "chile", "china",
  "colombia", "comoros", "congo", "croatia", "cuba", "cyprus", "czechia",
  "denmark", "djibouti", "dominica", "ecuador", "egypt", "estonia", "eswatini",
  "ethiopia", "fiji", "finland", "france", "gabon", "gambia", "georgia",
  "germany", "ghana", "greece", "grenada", "guatemala", "guinea", "guyana",
  "haiti", "honduras", "hungary", "iceland", "india", "indonesia", "iran", "iraq",
  "ireland", "israel", "italy", "jamaica", "japan", "jordan", "kazakhstan",
  "kenya", "kuwait", "kyrgyzstan", "laos", "latvia", "lebanon", "lesotho",
  "liberia", "libya", "liechtenstein", "lithuania", "luxembourg", "madagascar",
  "malawi", "malaysia", "maldives", "mali", "malta", "mauritania", "mauritius",
  "mexico", "moldova", "monaco", "mongolia", "montenegro", "morocco",
  "mozambique", "namibia", "nepal", "netherlands", "new zealand", "nicaragua",
  "niger", "nigeria", "north macedonia", "norway", "oman", "pakistan", "panama",
  "paraguay", "peru", "philippines", "poland", "portugal", "qatar", "romania",
  "russia", "rwanda", "samoa", "saudi arabia", "senegal", "serbia", "seychelles",
  "sierra leone", "singapore", "slovakia", "slovenia", "somalia", "south africa",
  "south korea", "south sudan", "spain", "sri lanka", "sudan", "suriname",
  "sweden", "switzerland", "syria", "taiwan", "tajikistan", "tanzania",
  "thailand", "togo", "tonga", "tunisia", "turkey", "turkmenistan", "uganda",
  "ukraine", "united arab emirates", "united kingdom", "united states", "uruguay",
  "uzbekistan", "vanuatu", "venezuela", "vietnam", "yemen", "zambia", "zimbabwe",
];

export const WORD_CHAIN_FOODS: string[] = [
  "apple", "apricot", "artichoke", "asparagus", "avocado", "bacon", "bagel",
  "banana", "basil", "bean", "beef", "beet", "biscuit", "blackberry", "blueberry",
  "bok choy", "bread", "broccoli", "brownie", "brussels sprout", "bun", "burrito",
  "butter", "cabbage", "cake", "candy", "cantaloupe", "caramel", "carrot",
  "cashew", "cauliflower", "caviar", "celery", "cheddar", "cheese", "cherry",
  "chicken", "chili", "chocolate", "chutney", "cinnamon", "clam", "coconut",
  "coffee", "cookie", "corn", "couscous", "crab", "cracker", "cranberry", "cream",
  "croissant", "cucumber", "cupcake", "curry", "dates", "dill", "donut", "duck",
  "dumpling", "edamame", "egg", "eggplant", "endive", "falafel", "fig", "fish",
  "flan", "flour", "fries", "frittata", "fudge", "garlic", "ginger", "gnocchi",
  "goat cheese", "gooseberry", "granola", "grape", "grapefruit", "gravy", "green bean",
  "guacamole", "gumbo", "halibut", "ham", "hazelnut", "honey", "hummus", "ice cream",
  "icing", "jalapeno", "jam", "jelly", "jerky", "juice", "kale", "kebab", "ketchup",
  "kiwi", "lamb", "lasagna", "leek", "lemon", "lentil", "lettuce", "lime", "lobster",
  "lychee", "macaroni", "mango", "maple syrup", "marshmallow", "mayonnaise", "meatball",
  "melon", "milk", "mint", "muffin", "mushroom", "mussel", "mustard", "nacho",
  "nectarine", "noodle", "nutmeg", "oatmeal", "octopus", "olive", "omelet", "onion",
  "orange", "oregano", "oyster", "pancake", "papaya", "parmesan", "parsley", "pasta",
  "peach", "peanut", "pear", "peas", "pecan", "pepper", "pesto", "pickle", "pie",
  "pineapple", "pistachio", "pizza", "plum", "popcorn", "pork", "potato", "pretzel",
  "pudding", "pumpkin", "quiche", "quinoa", "radish", "raisin", "raspberry", "rhubarb",
  "rice", "risotto", "rosemary", "saffron", "sage", "salad", "salmon", "salsa",
  "salt", "sandwich", "sardine", "sauce", "sausage", "scallop", "sesame", "shrimp",
  "smoothie", "sorbet", "soup", "soy sauce", "spinach", "squash", "steak", "strawberry",
  "sugar", "sushi", "sweet potato", "taco", "tangerine", "tapioca", "tea", "thyme",
  "toast", "toffee", "tomato", "tortilla", "truffle", "tuna", "turkey", "turnip",
  "vanilla", "vinegar", "waffle", "walnut", "wasabi", "watermelon", "wheat", "yogurt",
  "zucchini",
];

export const DRAW_PROMPTS: string[] = [
  "umbrella", "spaghetti", "jealousy", "earthquake", "dentist", "telescope",
  "accordion", "lighthouse", "yo-yo", "pancake", "zipper", "avalanche", "compass",
  "quicksand", "xylophone", "octopus", "narwhal", "jellyfish", "kangaroo",
  "volcano", "wizard", "whistle", "wheelchair", "yacht", "zeppelin", "quilt",
  "microphone", "helicopter", "giraffe", "fireworks", "cactus", "bicycle",
  "snowman", "sandcastle", "rainbow", "parachute", "mushroom", "moon", "ladder",
  "igloo", "hourglass", "harp", "grapes", "fountain", "dragon", "diamond",
  "castle", "bridge", "banana split", "astronaut", "anchor", "alarm clock",
  "backpack", "boomerang", "candle", "carousel", "chainsaw", "chandelier",
  "cookie jar", "crown", "dinosaur", "domino", "easel", "elevator", "envelope",
  "ferris wheel", "flashlight", "flamingo", "guitar", "hammock", "hedgehog",
  "hot air balloon", "iceberg", "jack-o-lantern", "kite", "laptop", "mailbox",
  "motorcycle", "paintbrush", "penguin", "pirate", "roller coaster", "saxophone",
  "scissors", "seesaw", "snorkel", "spaceship", "submarine", "tornado", "treasure chest",
  "trombone", "typewriter", "vampire", "violin", "windmill",
];

export const TWENTY_Q_HINTS: string[] = [
  "Is it a person?",
  "Is it a place?",
  "Is it an animal?",
  "Is it smaller than a breadbox?",
  "Could you hold it in one hand?",
  "Is it alive?",
  "Is it fictional?",
  "Is it edible?",
  "Would you find it indoors?",
  "Is it mostly one color?",
];

export const TRUTH_PROMPTS: string[] = [
  "What's something you've never told me?",
  "What's your most embarrassing memory from this year?",
  "If you could change one thing about our relationship, what would it be?",
  "What's a habit of mine that secretly drives you crazy?",
  "What's the weirdest thing you've ever Googled?",
  "What song always makes you think of us?",
  "What's a small thing I do that makes you feel loved?",
  "When did you realize you really liked me?",
  "What's a dream you've never shared out loud?",
  "What would your perfect day together look like?",
  "What's a movie you pretended to like for me?",
  "What's your guilty pleasure snack?",
  "What's something you're proud of but rarely mention?",
  "If we could teleport anywhere tonight, where?",
  "What's a fear you're working through?",
  "What nickname for me is secretly your favorite?",
  "What's the best advice you've ever received about love?",
  "What's a talent you wish you had?",
  "What's something you want us to do more often?",
  "What does 'home' mean to you now?",
];

export const DARE_PROMPTS: string[] = [
  "Do your best impression of me ordering food.",
  "Text your last contact a random emoji with no context.",
  "Speak in a British accent for the next 3 turns.",
  "Tell me something nice about my feet.",
  "Act out a movie scene until I guess it.",
  "Let me style your hair blindfolded for 60 seconds.",
  "Sing the chorus of your favorite song dramatically.",
  "Do 10 jumping jacks while complimenting me.",
  "Read the last note you wrote to yourself out loud.",
  "Give me a 30-second shoulder massage.",
  "Describe our relationship as a movie trailer.",
  "Wear socks on your hands until the next round.",
  "Do a slow-motion walk across the room.",
  "Let me draw a mustache on you with washable marker.",
  "Speak only in questions for the next 2 minutes.",
  "Make up a commercial for an absurd product.",
  "Plank while telling me three things you appreciate about me.",
  "Swap seats and finish the game from there.",
  "Do your best villain monologue about doing the dishes.",
  "End every sentence with 'darling' for three turns.",
];

export const WOULD_YOU_RATHER: string[] = [
  "Never be able to use your phone again OR never watch a movie or show again?",
  "Have hiccups forever OR always feel like you need to sneeze?",
  "Know when you're going to die OR how you're going to die?",
  "Fight 100 duck-sized horses OR 1 horse-sized duck?",
  "Always be slightly too cold OR always be slightly too warm?",
  "Only be able to whisper OR only be able to shout?",
  "Eat a spoonful of mayo every day for a year OR never eat pizza again?",
  "Have your search history made public OR all your texts from the past year?",
  "Lose all your photos OR lose all your music?",
  "Be famous but hated OR unknown but beloved?",
  "Time travel to the past OR to the future?",
  "Speak every language OR talk to animals?",
  "Win the lottery OR find true love (if you could only pick one)?",
  "Have free Wi‑Fi everywhere OR free coffee everywhere?",
  "Read minds OR become invisible?",
  "Never stop growing taller OR never age past 25?",
  "Always tell the truth OR always lie convincingly?",
  "Live without music OR live without books?",
  "Be a great singer OR a great dancer?",
  "Have perfect memory OR be endlessly creative?",
  "Explore space OR explore the deep ocean?",
  "Give up cheese OR give up chocolate?",
  "Relive one day on loop OR skip a year of life?",
  "Always be 10 minutes late OR 20 minutes early?",
  "Have no eyebrows OR no eyelashes?",
  "Sweat maple syrup OR sneeze glitter?",
  "Only eat sweet food OR only eat savory food?",
  "Be able to fly OR be able to breathe underwater?",
  "Know every language OR master every instrument?",
  "Have a pause button for life OR a rewind button (5 minutes only)?",
  "Never use social media again OR never eat dessert again?",
  "Always have to sing your thoughts OR dance everywhere you go?",
  "Be the funniest person alive OR the smartest person alive?",
  "Live in a treehouse OR live on a houseboat?",
  "Have a photographic memory OR an endless supply of patience?",
  "Only watch comedies forever OR only watch thrillers forever?",
  "Give up coffee OR give up tea?",
  "Be a morning person forever OR a night owl forever?",
  "Have unlimited books OR unlimited movies?",
  "Always cold pizza OR always burnt toast?",
  "Teleport randomly once a day OR time travel accidentally once a month?",
  "Have a third arm OR a third leg?",
  "Never wear shoes again OR never wear hats again?",
  "Speak only in movie quotes OR only in song lyrics?",
  "Win an Olympic gold OR win a Nobel Prize?",
  "Have perfect hair every day OR perfect skin every day?",
  "Be able to run fast OR lift heavy things easily?",
  "Live without AC OR live without heating?",
  "Only eat breakfast foods OR only eat dinner foods?",
  "Have a personal chef OR a personal driver?",
  "Give up pasta OR give up rice?",
  "Always know the weather OR always know the news?",
  "Be amazing at cooking OR amazing at baking?",
  "Have a pause in arguments OR an instant apology button?",
  "Never lose your keys OR never lose your phone?",
  "Always match outfits OR always clash fabulously?",
  "Speak with an accent you choose OR sing instead of talk one hour a day?",
  "Have endless snacks OR endless drinks?",
  "Be a cat person in a dog world OR a dog person in a cat world?",
  "Only travel by train OR only travel by boat?",
  "Have a rewind for conversations OR fast-forward through chores?",
  "Perfect handwriting OR perfect public speaking?",
  "Always wake up rested OR always fall asleep instantly?",
  "Give up spicy food OR give up crunchy food?",
  "Have a secret treehouse OR a secret library room?",
  "Never need sleep OR never need food?",
  "Be able to draw beautifully OR write beautifully?",
  "Only listen to live music OR only listen to studio recordings?",
  "Have a robot helper OR a genius pet?",
  "Always tell riddles OR always speak in puns?",
  "Win a cooking show OR win a trivia show?",
  "Have a cozy cabin OR a sleek city loft?",
  "Give up hugs OR give up high-fives?",
  "Always know the perfect gift OR always know the perfect words?",
  "Be a pirate OR be a knight?",
  "Have snow every Christmas OR sun every birthday?",
  "Only watch black-and-white films OR only read black-and-white comics?",
  "Have a magic carpet OR a magic bicycle?",
  "Speak softly forever OR laugh loudly forever?",
  "Never run out of socks OR never run out of batteries?",
  "Be amazing at puzzles OR amazing at sports?",
  "Have dinner with your hero OR learn a skill from your hero?",
  "Only eat food you cook OR only eat food others cook?",
  "Have a personal theme song OR a personal soundtrack?",
  "Always find parking OR always catch the green light?",
  "Give up podcasts OR give up audiobooks?",
  "Have a star named after you OR a plant species named after you?",
  "Be a great storyteller OR a great listener?",
  "Live next to the ocean OR next to the mountains?",
  "Have perfect rhythm OR perfect pitch?",
  "Only wear vintage fashion OR only wear futuristic fashion?",
  "Have a day with no obligations OR a night with no sleep needed?",
  "Be able to fix anything OR create anything from scratch?",
  "Always have clean dishes OR always have folded laundry?",
  "Give up ice cream OR give up pie?",
  "Have a photographic sense of smell OR perfect sense of direction?",
  "Win a dance battle OR a rap battle?",
  "Only play cooperative games OR only play competitive games?",
  "Have a hammock life OR a hot tub life?",
  "Speak every thought kindly OR hear every thought about you?",
  "Be a morning baker OR a midnight baker?",
  "Have unlimited notebooks OR unlimited pens?",
  "Always find money in old pockets OR always find time you forgot?",
  "Give up blankets OR give up pillows?",
  "Have a personal astronomer OR a personal historian?",
  "Be amazing at massages OR amazing at cooking breakfast?",
  "Only take baths OR only take showers?",
  "Have a secret talent revealed OR learn a partner's secret talent?",
  "Live in a silent film OR a musical?",
  "Have perfect Wi‑Fi OR perfect weather on command?",
  "Be a great planner OR a great improviser?",
  "Give up candles OR give up string lights?",
  "Have a library card with infinite holds OR a passport with infinite stamps?",
  "Always wake up to birdsong OR always wake up to ocean waves?",
  "Be a world-class hugger OR a world-class listener?",
  "Only eat food from trucks OR only eat food from fancy restaurants?",
  "Have a pocket dimension for snacks OR a pocket dimension for books?",
  "Win at chess every time OR win at cards every time?",
  "Have a cozy reading nook OR a sunny art studio?",
  "Give up popcorn OR give up pretzels?",
  "Be able to remember dreams OR control dreams?",
  "Have a perfect memory for dates OR a perfect memory for faces?",
  "Only listen to jazz OR only listen to classical?",
  "Have a personal barista OR a personal sommelier?",
  "Be amazing at karaoke OR amazing at trivia?",
  "Live without clocks OR live without calendars?",
  "Have endless board games OR endless card games?",
  "Always find the best seat OR always find the best snack?",
  "Give up morning coffee OR give up evening tea?",
  "Have a starry ceiling OR a sunny skylight?",
  "Be a great gift wrapper OR a great party host?",
  "Only watch documentaries OR only watch animated films?",
  "Have a magic fridge OR a magic closet?",
  "Speak only compliments for a day OR only ask questions for a day?",
  "Win a marathon OR win a bake-off?",
  "Have a personal poet OR a personal photographer?",
  "Give up waffles OR give up pancakes?",
  "Always travel light OR always travel luxuriously?",
  "Be a candle person OR a diffuser person?",
  "Have perfect handwriting notes OR perfect voice memos?",
  "Only play outside OR only play inside?",
  "Have a secret rooftop OR a secret basement lounge?",
  "Be great at planning trips OR great at planning surprises?",
  "Give up salsa OR give up guacamole?",
  "Have a bookshelf that reorganizes itself OR a pantry that restocks itself?",
  "Always find four-leaf clovers OR always find lucky pennies?",
  "Be a morning stretch person OR a midnight stretch person?",
  "Have unlimited puzzles OR unlimited coloring books?",
  "Only eat savory breakfast OR only eat sweet breakfast?",
  "Have a personal DJ OR a personal chef for dessert?",
  "Win a staring contest OR a thumb war championship?",
  "Give up handwritten letters OR give up voice notes?",
  "Have a fireplace OR a projector wall?",
  "Be amazing at charades OR amazing at Pictionary?",
  "Live in a cozy cottage OR a sleek penthouse?",
  "Have a perfect picnic spot OR a perfect stargazing spot?",
  "Only wear monochrome OR only wear patterns?",
  "Have a magic washing machine OR a magic dishwasher?",
  "Be a tea sommelier OR a coffee sommelier?",
  "Give up brunch OR give up midnight snacks?",
  "Have a bookshelf door OR a garden gate to nowhere?",
  "Always find the best playlist OR always find the best podcast episode?",
  "Be a great road trip DJ OR a great road trip navigator?",
  "Have endless candles OR endless plants?",
  "Only celebrate big holidays OR only celebrate tiny rituals?",
  "Have a personal astronomer for stargazing OR a personal chef for breakfast in bed?",
  "Win at trivia together OR win at escape rooms together?",
  "Give up board games OR give up video games?",
  "Have a hammock indoors OR a swing outdoors?",
  "Be a morning journal person OR an evening journal person?",
  "Have a fridge that suggests recipes OR a closet that suggests outfits?",
  "Only listen to vinyl OR only listen to live acoustic?",
  "Have a secret snack drawer OR a secret dessert freezer?",
  "Be amazing at slow dancing OR amazing at silly dancing?",
  "Live without spices OR live without sauces?",
  "Have a rooftop garden OR a basement workshop?",
  "Always find the comfiest blanket OR the comfiest chair?",
  "Give up movie nights OR give up game nights?",
  "Have a personal mixtape curator OR a personal book curator?",
  "Be a sunrise person OR a sunset person?",
  "Have a wall of postcards OR a jar of ticket stubs?",
  "Only eat seasonal food OR only eat comfort food?",
  "Have a magic oven OR a magic coffee maker?",
  "Win a cook-off together OR win a puzzle marathon together?",
  "Give up fresh flowers OR give up houseplants?",
  "Have a reading hour ritual OR a walking hour ritual?",
  "Be great at planning dates OR great at spontaneous dates?",
  "Have a chalkboard wall OR a magnet wall?",
  "Only play word games OR only play number games?",
  "Have a cozy attic OR a cozy basement den?",
  "Always find the perfect movie OR always find the perfect book?",
  "Be a breakfast-in-bed person OR a midnight-snack person?",
  "Have a personal stargazing map OR a personal coffee flavor wheel?",
  "Give up whipped cream OR give up sprinkles?",
  "Have a bookshelf ladder OR a kitchen ladder?",
  "Be amazing at toasts OR amazing at roasts (loving ones)?",
  "Live without mirrors OR live without clocks for a month?",
  "Have a secret dessert recipe OR a secret dance move?",
  "Only take bubble baths OR only take rain showers?",
  "Have a wall of polaroids OR a box of love letters?",
  "Be a picnic person OR a fancy dinner person?",
  "Have a magic spice rack OR a magic tea shelf?",
  "Win a karaoke duet OR a trivia duo?",
  "Give up candles during dinner OR give up music during dinner?",
  "Have a cozy window seat OR a cozy reading chair?",
  "Always find the best sunrise spot OR the best sunset spot?",
  "Be great at surprise gifts OR great at planned gifts?",
  "Have a personal sommelier for tea OR for chocolate?",
  "Only celebrate anniversaries OR only celebrate random Tuesdays?",
  "Have a bookshelf that glows OR a bed that floats (safely)?",
  "Be amazing at foot rubs OR amazing at scalp massages?",
  "Give up fuzzy socks OR give up silk pajamas?",
  "Have a secret snack vault OR a secret book vault?",
  "Win a bake-off as a team OR a puzzle hunt as a team?",
  "Have a fireplace reading hour OR a balcony stargazing hour?",
  "Be a morning coffee ritual person OR an evening tea ritual person?",
  "Have a magic cookie jar OR a magic fruit bowl?",
  "Only listen to rain sounds OR only listen to ocean sounds to sleep?",
  "Have a cozy blanket fort OR a cozy pillow fort?",
  "Always find the best brunch spot OR the best dessert spot?",
  "Be great at writing notes OR great at leaving voicemails?",
  "Have a personal playlist for walks OR a personal playlist for cooking?",
  "Give up whipped coffee OR give up cold brew?",
  "Have a bookshelf organized by color OR by mood?",
  "Be amazing at slow mornings OR amazing at slow evenings?",
  "Live without dessert OR live without appetizers for a year?",
  "Have a secret hot cocoa bar OR a secret lemonade stand?",
  "Win a dance-off in the kitchen OR a sing-off in the car?",
  "Have a cozy rainy day kit OR a cozy sunny day kit?",
  "Be a letters-in-the-mail person OR a voice-memo person?",
  "Have a magic picnic basket OR a magic movie projector?",
  "Only play cooperative puzzles OR only play competitive card games?",
  "Have a wall of favorite quotes OR a jar of favorite memories?",
  "Be great at planning vacations OR great at planning staycations?",
  "Give up fresh bread OR give up fresh fruit for a month?",
  "Have a rooftop telescope OR a kitchen microscope for fun?",
  "Always find the best playlist for cleaning OR the best playlist for cuddling?",
  "Be amazing at surprise breakfasts OR amazing at surprise dinners?",
  "Have a secret bookshelf room OR a secret vinyl listening room?",
  "Win a two-player video game marathon OR a board game marathon?",
  "Have a cozy winter nook OR a breezy summer nook?",
  "Be a handwritten recipe person OR a digital recipe person?",
  "Have a magic blanket that warms OR a magic fan that cools?",
  "Give up movie popcorn OR give up movie candy?",
  "Have a personal barista for mornings OR a personal bartender for evenings?",
  "Only watch sunrises together OR only watch sunsets together for a year?",
  "Have a bookshelf of love stories OR a shelf of travel guides?",
  "Be great at building forts OR great at building playlists?",
  "Have a secret dessert tasting menu OR a secret cheese tasting night?",
  "Win a couples trivia night OR a couples cook night?",
  "Give up matching pajamas OR give up matching mugs?",
  "Have a cozy reading light OR a cozy string light canopy?",
  "Always find the best hiking trail OR the best coffee shop?",
  "Be amazing at slow dancing in the kitchen OR slow dancing in the living room?",
  "Have a magic journal that suggests prompts OR a magic calendar that plans dates?",
  "Only celebrate with cake OR only celebrate with pie?",
  "Have a bookshelf of poetry OR a shelf of cookbooks?",
  "Be a morning stretch-together person OR an evening unwind-together person?",
  "Have a secret s'mores kit OR a secret fondue kit?",
  "Win a two-player word game streak OR a two-player card game streak?",
  "Give up cozy socks OR give up cozy robes?",
  "Have a wall map with pins OR a globe on the desk?",
  "Be great at planning picnics OR planning road trips?",
  "Have a magic spice drawer OR a magic tea drawer?",
  "Only listen to instrumental music OR only listen to acapella for a week?",
  "Have a cozy cat nap spot OR a cozy sunbeam spot?",
  "Always find the best dumplings OR the best tacos?",
  "Be amazing at breakfast dates OR amazing at midnight snack dates?",
  "Have a secret puzzle table OR a secret game table?",
  "Win a gingerbread house contest OR a sandcastle contest?",
  "Give up handwritten calendars OR give up digital reminders?",
  "Have a bookshelf of mysteries OR a shelf of rom-coms?",
  "Be a stargazing blanket person OR a beach blanket person?",
  "Have a magic cookie sheet OR a magic pizza stone?",
  "Only play charades OR only play Pictionary for a month?",
  "Have a cozy record player corner OR a cozy synth corner?",
  "Always find the best ramen OR the best pho?",
  "Be great at surprise notes OR surprise playlists?",
  "Have a personal barista lesson OR a personal cocktail lesson?",
  "Give up brunch dates OR give up dinner dates for a month?",
  "Have a secret hot chocolate flavors OR a secret tea flavors collection?",
  "Win a couples scavenger hunt OR a couples photo challenge?",
  "Have a cozy bay window OR a cozy balcony swing?",
  "Be amazing at planning lazy Sundays OR planning adventurous Saturdays?",
  "Have a magic bookmark OR a magic recipe card box?",
  "Only celebrate with balloons OR only celebrate with confetti?",
  "Have a bookshelf of travel memoirs OR a shelf of cook's memoirs?",
  "Be a sunrise coffee person OR a sunset tea person?",
  "Have a secret board game shelf OR a secret card game tin collection?",
  "Win a two-player cooperative escape OR a two-player cooperative cook?",
  "Give up fuzzy blankets OR give up weighted blankets?",
  "Have a cozy fireplace book OR a cozy beach read stack?",
  "Always find the best croissant OR the best bagel?",
  "Be great at planning surprise staycations OR surprise day trips?",
  "Have a magic oven mitt OR a magic apron?",
  "Only listen to jazz in the morning OR classical at night?",
  "Have a cozy loft bed OR a cozy floor mattress fort?",
  "Be amazing at writing love letters OR amazing at reading aloud?",
  "Have a secret dessert cookbook OR a secret cocktail book?",
  "Win a puzzle-a-thon OR a read-a-thon together?",
  "Give up movie marathons OR give up series marathons?",
  "Have a bookshelf of short stories OR a shelf of long novels?",
  "Be a candlelit dinner person OR a string-lights dinner person?",
  "Have a magic picnic blanket OR a magic beach towel?",
  "Only celebrate with dancing OR only celebrate with singing?",
  "Have a cozy writing desk OR a cozy painting desk?",
  "Always find the best sushi OR the best sashimi?",
  "Be great at planning cozy nights in OR exciting nights out?",
  "Have a personal sommelier for cheese OR for chocolate pairings?",
  "Give up morning stretches together OR evening stretches together?",
  "Have a secret hot toddy kit OR a secret iced tea kit?",
  "Win a two-player trivia sprint OR a two-player word sprint?",
  "Have a cozy window herb garden OR a cozy windowsill succulent shelf?",
  "Be amazing at building pillow forts OR blanket forts?",
  "Have a magic measuring cup OR a magic timer?",
  "Only play card games in bed OR only play dice games in bed?",
  "Have a bookshelf of essays OR a shelf of graphic novels?",
  "Be a hot cocoa person OR an apple cider person?",
  "Have a secret fondue night OR a secret raclette night?",
  "Win a couples baking day OR a couples puzzle day?",
  "Give up matching slippers OR matching robes?",
  "Have a cozy attic library OR a cozy basement cinema?",
  "Always find the best pho OR the best ramen spot?",
  "Be great at planning surprise breakfasts OR surprise lunches?",
  "Have a magic whisk OR a magic wooden spoon?",
  "Only listen to podcasts on walks OR audiobooks on walks?",
  "Have a cozy beanbag nook OR a cozy papasan nook?",
  "Be amazing at slow Sunday mornings OR slow Friday nights?",
  "Have a secret scone recipe OR a secret muffin recipe?",
  "Win a two-player strategy game night OR a two-player party game night?",
  "Give up fresh orange juice OR fresh apple juice?",
  "Have a bookshelf of biographies OR a shelf of science books?",
  "Be a sunrise jog person OR a sunset stroll person?",
  "Have a magic cutting board OR a magic mixing bowl?",
  "Only celebrate with flowers OR only celebrate with candles?",
  "Have a cozy kitchen island OR a cozy dining nook?",
  "Always find the best dim sum OR the best tapas?",
  "Be great at planning themed dinners OR themed movie nights?",
  "Have a personal playlist for stargazing OR for rainy days?",
  "Give up cozy throws OR cozy cushions?",
  "Have a secret ice cream flavor lineup OR a secret gelato night?",
  "Win a couples origami challenge OR a couples sketch challenge?",
  "Have a cozy hammock chair OR a cozy hanging chair?",
  "Be amazing at planning surprise picnics OR surprise hikes?",
  "Have a magic tea kettle OR a magic French press?",
  "Only play cooperative board games OR cooperative card games?",
  "Have a bookshelf of myths OR a shelf of fairy tales?",
  "Be a mulled wine person OR a spiced cider person?",
  "Have a secret charcuterie board kit OR a secret cheese fondue kit?",
  "Win a two-player Scrabble streak OR a two-player Boggle streak?",
  "Give up morning pastries OR evening desserts?",
  "Have a cozy radiator cat seat OR a cozy sunny windowsill?",
  "Always find the best bubble tea OR the best smoothie bowl?",
  "Be great at planning lazy brunches OR lazy dinners?",
  "Have a magic salt cellar OR a magic pepper grinder?",
  "Only listen to piano music OR guitar music for a week?",
  "Have a cozy daybed OR a cozy chaise lounge?",
  "Be amazing at writing bucket lists OR amazing at completing them?",
  "Have a secret crepe night OR a secret waffle night?",
  "Win a couples jigsaw relay OR a couples crossword relay?",
  "Give up scented candles OR essential oil diffusers?",
  "Have a bookshelf of plays OR a shelf of screenplays?",
  "Be a blanket hog OR a pillow hog (hypothetically)?",
  "Have a magic toaster OR a magic blender?",
  "Only celebrate with cake pops OR with cupcakes?",
  "Have a cozy mudroom bench OR a cozy entryway mirror?",
  "Always find the best churros OR the best beignets?",
  "Be great at planning surprise movie nights OR surprise game nights?",
  "Have a personal barista for decaf OR a personal mixologist for mocktails?",
  "Give up cozy cardigans OR cozy hoodies?",
  "Have a secret midnight pancake tradition OR a secret midnight popcorn tradition?",
  "Win a two-player Codenames-style clue game OR a two-player word association duel?",
  "Have a cozy plant wall OR a cozy art wall?",
  "Be amazing at planning cozy reading dates OR cozy sketch dates?",
  "Have a magic pie dish OR a magic tart pan?",
  "Only play word association OR only play rhyming games for an hour?",
  "Have a bookshelf of cook zines OR a shelf of travel zines?",
  "Be a croissant person OR a pain au chocolat person?",
  "Have a secret tiramisu night OR a secret panna cotta night?",
  "Win a couples tongue-twister contest OR a couples riddle contest?",
  "Give up fuzzy robes OR silky robes?",
  "Have a cozy bench by the window OR a cozy chair by the fire?",
  "Always find the best gelato OR the best soft serve?",
  "Be great at planning surprise playlists OR surprise letters?",
  "Have a magic rolling pin OR a magic pastry brush?",
  "Only listen to lo-fi OR listen to white noise to focus?",
  "Have a cozy loft reading net OR a cozy corner bookshelf?",
  "Be amazing at planning breakfast for dinner OR dinner for breakfast?",
  "Have a secret churro party OR a secret donut party?",
  "Win a two-player hangman championship OR a two-player word chain sprint?",
];
